# Generated by Django 5.0 on 2026-09-24 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_to_recruiters', models.BooleanField(default=True, verbose_name='Let recruiters view my profile')),
                ('show_email', models.BooleanField(default=False, verbose_name='Show my email address')),
                ('show_skills', models.BooleanField(default=True, verbose_name='Show my skills')),
                ('show_education', models.BooleanField(default=True, verbose_name='Show my education')),
                ('show_experience', models.BooleanField(default=True, verbose_name='Show my work experience')),
                ('show_links', models.BooleanField(default=True, verbose_name='Show my links')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy', to='profiles.profile')),
            ],
        ),
    ]
